version: '3.8'

services:
  expshop:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/uploads:/app/backend/uploads
    restart: unless-stopped
